## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring.application.name=ProjectDashboard
server.port=8080

# MySQL Verbindung
spring.datasource.url=jdbc:mysql://5.83.145.47:3306/FOM_Project?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=fom_admin
spring.datasource.password=mrv4PXuTS74m%jg^!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Einstellungen
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect



